### ISSUE TITLE
International date line where it should not be

### ISSUE THREAD

**Issue by aaime** [pka/mvt-benchmark#12]
![Selezione_916](https://user-images.githubusercontent.com/325433/64906117-5647a680-d6e2-11e9-83b6-e40f42fa7fd9.png)

Not sure if it's a data problem or a reprojection problem, but I don't remember the international date line being where the map says it is :-D

**Comment by pka** [comment]
After creating a new Natural Earth extract, I finally investigated this problem. And it was indeed caused by ogr2ogr reprojecting to Web Mercator. I fixed it by omitting the date line in the data source...
